create table if not exists public.checkins (
  id bigint generated by default as identity primary key,
  student_name text not null,
  class_time text not null,
  created_at timestamptz not null default now()
);

alter table public.checkins enable row level security;

create policy "checkins_select"
on public.checkins
for select
to anon
using (true);

create policy "checkins_insert"
on public.checkins
for insert
to anon
with check (true);
